export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const FETCH_CART_ITEMS = 'FETCH_CART_ITEMS';
export const ADD_MORE_FUNDS = 'ADD_MORE_FUNDS';
export const PURCHASE_ITEMS = 'PURCHASE_ITEMS';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAIL = 'PURCHASE_FAIL';
export const FETCH_MY_BOOKS = 'FETCH_MY_BOOKS';

export const FETCH_STORE_ITEMS = 'FETCH_STORE_ITEMS';
export const FILTER_STORE_ITEMS = 'FILTER_STORE_ITEMS';
export const FILTER_STORE_START = 'FILTER_STORE_START';
export const FILTER_STORE_COMPLETE = 'FILTER_STORE_COMPLETE';
export const FETCH_BOOK = 'FETCH_BOOK';
export const UPDATE_PURCHASE_STATE = 'UPDATE_PURCHASE_STATE';